define o = Character(o, color="c8ffc8")
define x = Character(x, color="c8ffc8")
define k = Character(k, color="c8ffc8")
define b = Character("Mrs. Oliver", color = "c8ffc8")
define z = Character("The Doctor", color="c8ffc8")
define p = Character("Mrs. ???", color="c8ffc8")
define j = Character(j, color="c8ffc8")
define m = Character("Mr.Pickles", color="c8ffc8")
define c = Character("Ms. Clover", color="c8ffc8")